Issue #2071 - Manual application of patch  dspace_5x_irus_patch.diff.
This is from https://atmire.github.io/IRUS/#/.

Was unable to automatically apply patch using git apply --check <patch> in dspace directory.

git apply --check dspace_5x_irus_patch.diff
error: dspace/config/modules/stats.cfg: already exists in working directory
error: dspace/config/spring/xmlui/open-url-listeners.xml: already exists in working directory
error: dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/src/main/java/com/atmire/statistics/export/ExportUsageEventListener.java: already exists in working directory
error: patch failed: dspace/modules/xmlui/pom.xml:193
error: dspace/modules/xmlui/pom.xml: patch does not apply

This error occured because DSpace is customised.

After making changes given in patch had to do the following extra changes to get Dspace to compile:

(1) Had to change patch new file dspace/modules/atmire-statistics-exporter/atmire-statistics-exporter-api/pom.xml content for <parent> from
    <parent>
        <groupId>org.dspace</groupId>
       <artifactId>modules</artifactId>
       <version>[5.0,5.*]</version>
    </parent>
to
     <parent>
        <groupId>org.dspace</groupId>
        <artifactId>modules</artifactId>
        <version>5.11-SNAPSHOT</version>
		<relativePath>..</relativePath>
    </parent>

(2) Delete old IRUSUK module dspace/modules/additions/src/main/java/uk/ac/edina/datashare/irusuk